# From https://github.com/duritong/puppet_catalog_test
source 'https://rubygems.org'
gem 'puppet', '3.4.3'
gem 'hiera'

gem 'rails', '2.3.14'
# for simple exported resources
gem 'activerecord', '2.3.14'

# additional gems you need
gem 'trocla'
