#!/bin/bash

set -euo pipefail

wait_for_clean() {
    printf "=======> wait for 'dbctl config diff' to be clean: "
    while ! sudo dbctl config diff > /dev/null; do
        printf .
        sleep 5
    done
    echo "OK"
}

if [ $# -lt 2 ]; then
    prog=${0##*/}
    echo "Usage:"
    echo "    $prog INSTANCE REASON"
    echo
    echo "Depools a database instance, and waits for up to 5 minutes for all"
    echo "wikiuser202206/wikiadmin/dump/root db processes to end."
    echo
    echo "E.g.:"
    echo "    $prog db1139:3316 'schema change T259831'"
    exit 0
fi

instance="$1"; shift
reason="$1"; shift

echo "=======> checking the instance exists"
dbctl instance "$instance" get > /dev/null

wait_for_clean

echo "=======> depooling"
sudo dbctl instance "$instance" depool
sudo dbctl config diff || :
sudo dbctl config commit -b -m "$instance depooling: $reason"

printf "=======> Wait for wikiuser202206/wikiadmin/dump/root connections to finish: "
for i in {1..60}; do
    sleep 5
    if [ $(sudo db-mysql "$instance" -BN -e "select count(*) from information_schema.processlist where user regexp '(wikiuser202206|wikiadmin|dump|root)'") == 1 ]; then
        # == 1 because the check itself will generate one entry for 'root'
        echo " OK"
        exit 0
    fi
    printf .
done

echo " ERROR: db is still busy"
exit 1
