#!/bin/bash
# This turns an upstream MariaDB static tarball into a deb.

control=$1

if [ ! -e $control ]; then
	echo "missing control" 1>&2
	exit 1
fi

confirm() {
	read -p "continue? yes/no " yn
	if [[ ! "$yn" =~ ^y ]]; then
		echo "abort"
		exit 1
	fi
}

package=$(grep 'Package:' $control | awk '{print $2}')
vendor=$(echo $package | sed 's/wmf-\(mariadb\|mysql\).*/\1/')
release=$(grep 'Version:' $control | awk '{print $2}')
version=$(echo $release | sed 's/\(.*\)-.*/\1/')
debname="${package}_${release}_amd64"
tarball="${vendor}-${version}-linux-x86_64.tar.gz"
optname="${package}"
tarname=$(echo $tarball | sed 's/\.tar\.gz$//')
makedir="$debname"
basedir="/opt/$optname"
initinstall=""
initrm=""

echo "control: $control"
echo "package: $package"
echo "release: $release"
echo "version: $version"
echo "tarname: $tarname"
echo "makedir: $makedir"
echo "basedir: $basedir"

confirm

if [ ! -e $tarball ]; then
	echo "missing tarball" 1>&2
	exit 1
fi

echo "creating directory structure..."

rm -rf $makedir
mkdir $makedir

mkdir $makedir/DEBIAN 
cp $control $makedir/DEBIAN/control

mkdir $makedir/opt

echo "extracting tarball..."

tar zxpf $tarball -C $makedir/opt
mv $makedir/opt/$tarname $makedir/opt/$optname

echo "adding WMF stuff..."

# install systemd unit on stretch or higher
if [[ ! "$(cat /etc/debian_version)" < "9" ]]; then
    initinstall="/bin/systemctl daemon-reload"
    initrm="/bin/systemctl daemon-reload"
    mkdir -p $makedir/etc/systemd/system
    cat $vendor.service | sed "s:BASEDIR:/opt/${optname}/:g" > $makedir/etc/systemd/system/$vendor.service
fi

postinst="$makedir/DEBIAN/postinst"
cat mariadb-deb-postinst.tpl.sh | sed "s:BASEDIR:$basedir:g" | sed "s:INITINSTALL:$initinstall:g" > $postinst
chmod 755 $postinst

postrm="$makedir/DEBIAN/postrm"
cat mariadb-deb-postrm.tpl.sh | sed "s:BASEDIR:$basedir:g" | sed "s:INITRM:$initrm:g" > $postrm
chmod 755 $postrm

echo "removing unneeded files"
# suite test
rm -Rf $makedir/opt/$optname/mysql-test
# embebbed mysql & test binaries
rm -f $makedir/opt/$optname/bin/mysql_client_test_embedded
rm -f $makedir/opt/$optname/bin/mysqltest_embedded
rm -f $makedir/opt/$optname/bin/mysql_embedded
rm -f $makedir/opt/$optname/bin/mysql_client_test

# making root the owner

chown -R root:root $makedir
echo "Now building the package (this may take a while)..."
dpkg-deb --build $makedir

echo "done."
