#!/bin/bash

set -euo pipefail

# Script to find the current position of a master db's binlog, and output
# the relevant `change master` command to start replicating from that point.

if [ $# -eq 0 -o $# -gt 2 ]; then
    echo "Usage:"
    echo "    ${0##*/} DB_INSTANCE_FQDN [PORT]"
    exit 0
fi

host="$1"; shift
port="${1:-3306}"

if ! echo $host | grep -q '\.'; then
    echo "ERROR: hostname needs to be fqdn"
    exit 1
fi

# Get current binlog file and position
read file pos < <(sudo -H mysql.py -h "${host}" -P "${port}" -BN -e 'show master status')

echo "=======> Host: $host"
echo "=======> File: ${file:?}"
echo "=======> Pos: ${pos:?}"
echo
echo "change master to master_host='$host', master_port=$port, master_ssl=1, master_log_file='$file', master_log_pos=$pos, master_user='repl', master_password='x';"
