#!/bin/sh
section=$1
db-mysql -BN db2093 zarcillo -e "SELECT instances.server, instances.port FROM instances JOIN section_instances ON instances.name = section_instances.instance WHERE section_instances.section IN ('$section', 'test-$section')  ORDER BY instances.name DESC"
