#!/bin/sh
section=$1
db-mysql db1215 -BN  zarcillo -e "SELECT instances.name FROM instances JOIN section_instances ON instances.name = section_instances.instance LEFT JOIN masters ON masters.instance = instances.name WHERE section_instances.section IN ('$section', 'test-$section') ORDER BY masters.section, instances.name DESC"
