#!/bin/bash
# Largely taken from:
# https://github.com/duritong/puppet_catalog_test
#
# modifications (c) 2014 Wikimedia Foundation
#
#set -x
if [ -z $1 ] || [ -z $2 ] || [ -z $3 ]; then
  echo "USAGE: $0 <PUPPET_VERSION> <FQDN> <OUTPUT_DIR> [CHANGE_ID]"
  exit 1
fi

if [ -z $4 ]; then
    CHANGE="production"
else
    CHANGE=${4}
fi;

ETCDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PUPPET_VERSION=${1}
MY_GEMDIR=${ETCDIR}/env_puppet_${PUPPET_VERSION}
PARENT=$(readlink -f ${ETCDIR}/../)

# We need to ensure we're working from here I guess given we need the
# Gemfile to be local to the CWD
pushd ${MY_GEMDIR}



PUPPET_VERSION=${1}
if [ "${CHANGE}" == "production" ]; then
    EXTDIR=${PARENT}/external
else
    EXTDIR=${PARENT}/external/change/${CHANGE}
fi;

PUPPETDIR=${EXTDIR}/puppet
CATALOG_DIR=${3}/puppet_catalogs_${1}_${CHANGE}

test -d $CATALOG_DIR || mkdir -p $CATALOG_DIR

OUTPUT_FILE=$CATALOG_DIR/$2.out
CATALOG_FILE=$CATALOG_DIR/$2.pson
TIME_FILE=$CATALOG_DIR/$2.time
WARNINGS_FILE=$CATALOG_DIR/$2.warnings

if [ "$PUPPET_VERSION" == "3" ]; then
    COMPILE_OPTIONS="--storeconfigs true --thin_storeconfigs true --dbadapter mysql --dbserver localhost --dbuser puppet --dbpassword puppet"
else
    # storeconfigs gets you issues with compiling 2.7 catalogs
    # Verified on palladium, with storeconfigs the format of compiled catalogs changes in 2.7
    COMPILE_OPTIONS="--factsync true"
fi

bundle exec puppet master \
  --modulepath=$PUPPETDIR/modules/:$PUPPETDIR/modules/site \
  --manifestdir $PUPPETDIR/manifests \
  --yamldir $EXTDIR/var/yaml \
  --templatedir $PUPPETDIR/templates \
  --confdir $EXTDIR/etc \
  --vardir $EXTDIR/var \
  --masterlog $CATALOG_DIR/master.log \
  --pluginsync true $COMPILE_OPTIONS\
  --trace \
  --color false \
  --compile $2 > $OUTPUT_FILE 2> $WARNINGS_FILE

RETCODE=$?

grep -E '^(.*0;36m)?notice: Compiled catalog for ' $OUTPUT_FILE | head -n 1 | sed 's/.*in \(.*\) seconds.*/\1/' > $TIME_FILE
grep -E '^(.*0;33m)?warning:' $OUTPUT_FILE >> $WARNINGS_FILE
grep -vE '^(.*0;33m)?(Info|[Nn]otice|[Ww]arning):' $OUTPUT_FILE > $CATALOG_FILE
exit $RETCODE
