#!/bin/bash
# Largely taken from:
# https://github.com/duritong/puppet_catalog_test
#
# modifications (c) 2014 Wikimedia Foundation
#
if [ -z $1 ] || [ -z $2 ] || [ -z $3 ]; then
  echo "USAGE: $0 <PUPPET_VERSION> <FQDN> <OUTPUT_DIR>"
fi

ETCDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# We need to ensure we're working from here I guess given we need the
# Gemfile to be local to the CWD
pushd ${ETCDIR}


test -f Gemfile && (diff -Naur Gemfile.$1 Gemfile > /dev/null)
if [ $? -gt 0 ]; then
  [ -f Gemfile.lock ] && rm Gemfile.lock
  cp Gemfile.$1 Gemfile
fi
test -f Gemfile.lock ||  bundle > /dev/null

PARENT=$(readlink -f ${ETCDIR}/../)
EXTDIR=${PARENT}/external
PUPPETDIR=${PARENT}/external/puppet
CATALOG_DIR=${3}/puppet_catalogs_${1}

test -d $CATALOG_DIR || mkdir $CATALOG_DIR

OUTPUT_FILE=$CATALOG_DIR/$2.out
CATALOG_FILE=$CATALOG_DIR/$2.pson
TIME_FILE=$CATALOG_DIR/$2.time
WARNINGS_FILE=$CATALOG_DIR/$2.warnings

if [ "$1" == "3" ]; then
    COMPILE_OPTIONS="--storeconfigs true --thin_storeconfigs true"
else
    #storeconfigs gets you issues with compiling 2.7 catalogs
    COMPILE_OPTIONS="--factsync true"
fi


bundle exec puppet master \
  --modulepath=$PUPPETDIR/modules/:$PUPPETDIR/modules/site \
  --manifestdir $PUPPETDIR/manifests \
  --yamldir $EXTDIR/var/yaml \
  --templatedir $PUPPETDIR/templates \
  --confdir $ETCDIR/etc \
  --vardir $ETCDIR/var \
  --masterlog $CATALOG_DIR/master.log \
  --pluginsync true $COMPILE_OPTIONS\
  --trace \
  --color false \
  --compile $2 > $OUTPUT_FILE 2> $WARNINGS_FILE

RETCODE=$?

grep -E '^(.*0;36m)?notice: Compiled catalog for ' $OUTPUT_FILE | head -n 1 | sed 's/.*in \(.*\) seconds.*/\1/' > $TIME_FILE
grep -E '^(.*0;33m)?warning:' $OUTPUT_FILE >> $WARNINGS_FILE
grep -vE '^(.*0;33m)?(Info|[Nn]otice|[Ww]arning):' $OUTPUT_FILE > $CATALOG_FILE
popd
exit $RETCODE
