#!/bin/bash
if [ -z $1 ] || [ -z $2 ] || [ -z $3 ] || [ -z $4 ]; then
    echo "USAGE: $0 <FQDN> <OUTPUT_DIR> <OLD_CATALOG_DIR> <NEW_CATALOG_DIR> "
    exit 1
fi;


ETCDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $ETCDIR
test -f Gemfile && (diff -Naur Gemfile.3 Gemfile > /dev/null)
if [ $? -gt 0 ]; then
  [ -f Gemfile.lock ] && rm Gemfile.lock
  cp Gemfile.3 Gemfile
fi
test -f Gemfile.lock ||  bundle > /dev/null


OLD_CATALOG_DIR=${3}
NEW_CATALOG_DIR=${4}


PARENT=$(readlink -f ${ETCDIR}/../)
OUT_DIR=${2}
OUTPUT_FILE=${OUT_DIR}/${1}.diff

test -d ${OUT_DIR} || mkdir -p ${OUT_DIR}
bundle exec puppet catalog diff --content_diff ${OLD_CATALOG_DIR}/${1}.pson ${NEW_CATALOG_DIR}/${1}.pson > ${OUTPUT_FILE}
popd
