#!/bin/bash
if [ -z $1 ]; then
    echo "USAGE: $0 <PUPPET_VERSION>"
fi

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MY_GEMDIR=${MYDIR}/env_puppet_${1}
pushd ${MY_GEMDIR}
bundle --deployment install
popd
