#!/bin/bash
if [ -z $1 ] || [ -z $2 ]; then
    usage
    exit 1
fi;

function usage () {
    echo "$0: <CHANGE> <REVISION>"
}

CHANGE=${1}
REVISION=${2}
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Preparing the dir for change ${CHANGE}"
${DIR}/helper install ${CHANGE} ${REVISION}
PARENT=$(readlink -f ${DIR}/../)
