#!/bin/bash

cd /svnroot/git-dumps/mediawiki/core

git remote add origin ssh://localhost:29418/mediawiki/core.git
git config --add remote.origin.push '+refs/heads/*:refs/heads/*'
git config --add remote.origin.push '+refs/tags/*:refs/tags/*'
git push origin master
