#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

if [ $# -ne 1 ]; then
    prog=${0##*/}
    echo "Usage:"
    echo "    $prog INSTANCE"
    echo
    echo "Applies the sys schema to the database instance"
    echo
    echo "E.g.:"
    echo "    $prog db2088:3318"
    set +e
    [ $# -eq 0 ]
    exit
fi

inst="${1}"

(
    echo 'set session sql_log_bin=0;'
    echo 'create database if not exists sys;'
    echo 'use sys;'
    cat extract_schema_from_file_name.sql \
        extract_table_from_file_name.sql \
        format_bytes.sql \
        format_path.sql \
        format_statement.sql \
        format_time.sql \
        sys.sql
) | sudo -H mysql.py -h "$inst"
